/* ─────────────────────────────────────────────────────────────────
   NSE STOCK LIST — used for local typeahead search in the Add Stock modal.
   Covers Nifty 50, Nifty Next 50, and popular mid-cap stocks.
   Symbol = NSE ticker (used as SYMBOL.NS for Yahoo Finance price fetch).
   ───────────────────────────────────────────────────────────────── */
export const NSE_STOCKS = [
  // ── NIFTY 50 ──────────────────────────────────────────────────
  { symbol: 'RELIANCE',    name: 'Reliance Industries Ltd' },
  { symbol: 'TCS',         name: 'Tata Consultancy Services Ltd' },
  { symbol: 'HDFCBANK',    name: 'HDFC Bank Ltd' },
  { symbol: 'ICICIBANK',   name: 'ICICI Bank Ltd' },
  { symbol: 'INFY',        name: 'Infosys Ltd' },
  { symbol: 'HINDUNILVR',  name: 'Hindustan Unilever Ltd' },
  { symbol: 'ITC',         name: 'ITC Ltd' },
  { symbol: 'SBIN',        name: 'State Bank of India' },
  { symbol: 'BHARTIARTL',  name: 'Bharti Airtel Ltd' },
  { symbol: 'AXISBANK',    name: 'Axis Bank Ltd' },
  { symbol: 'BAJFINANCE',  name: 'Bajaj Finance Ltd' },
  { symbol: 'LT',          name: 'Larsen & Toubro Ltd' },
  { symbol: 'KOTAKBANK',   name: 'Kotak Mahindra Bank Ltd' },
  { symbol: 'ASIANPAINT',  name: 'Asian Paints Ltd' },
  { symbol: 'MARUTI',      name: 'Maruti Suzuki India Ltd' },
  { symbol: 'NESTLEIND',   name: 'Nestle India Ltd' },
  { symbol: 'TITAN',       name: 'Titan Company Ltd' },
  { symbol: 'POWERGRID',   name: 'Power Grid Corporation of India Ltd' },
  { symbol: 'NTPC',        name: 'NTPC Ltd' },
  { symbol: 'ULTRACEMCO',  name: 'UltraTech Cement Ltd' },
  { symbol: 'MM',          name: 'Mahindra & Mahindra Ltd' },
  { symbol: 'TECHM',       name: 'Tech Mahindra Ltd' },
  { symbol: 'WIPRO',       name: 'Wipro Ltd' },
  { symbol: 'ADANIENT',    name: 'Adani Enterprises Ltd' },
  { symbol: 'ADANIPORTS',  name: 'Adani Ports and SEZ Ltd' },
  { symbol: 'JSWSTEEL',    name: 'JSW Steel Ltd' },
  { symbol: 'TATAMOTORS',  name: 'Tata Motors Ltd' },
  { symbol: 'TATASTEEL',   name: 'Tata Steel Ltd' },
  { symbol: 'HCLTECH',     name: 'HCL Technologies Ltd' },
  { symbol: 'SUNPHARMA',   name: 'Sun Pharmaceutical Industries Ltd' },
  { symbol: 'CIPLA',       name: 'Cipla Ltd' },
  { symbol: 'DRREDDY',     name: 'Dr. Reddy\'s Laboratories Ltd' },
  { symbol: 'DIVISLAB',    name: 'Divi\'s Laboratories Ltd' },
  { symbol: 'BAJAJFINSV',  name: 'Bajaj Finserv Ltd' },
  { symbol: 'BAJAJ-AUTO',  name: 'Bajaj Auto Ltd' },
  { symbol: 'HEROMOTOCO',  name: 'Hero MotoCorp Ltd' },
  { symbol: 'BRITANNIA',   name: 'Britannia Industries Ltd' },
  { symbol: 'EICHERMOT',   name: 'Eicher Motors Ltd' },
  { symbol: 'COALINDIA',   name: 'Coal India Ltd' },
  { symbol: 'GRASIM',      name: 'Grasim Industries Ltd' },
  { symbol: 'INDUSINDBK',  name: 'IndusInd Bank Ltd' },
  { symbol: 'SHREECEM',    name: 'Shree Cement Ltd' },
  { symbol: 'HINDALCO',    name: 'Hindalco Industries Ltd' },
  { symbol: 'BPCL',        name: 'Bharat Petroleum Corporation Ltd' },
  { symbol: 'ONGC',        name: 'Oil and Natural Gas Corporation Ltd' },
  { symbol: 'IOC',         name: 'Indian Oil Corporation Ltd' },
  { symbol: 'APOLLOHOSP',  name: 'Apollo Hospitals Enterprise Ltd' },
  { symbol: 'LTIM',        name: 'LTIMindtree Ltd' },
  { symbol: 'SBILIFE',     name: 'SBI Life Insurance Company Ltd' },
  { symbol: 'HDFCLIFE',    name: 'HDFC Life Insurance Company Ltd' },

  // ── NIFTY NEXT 50 ─────────────────────────────────────────────
  { symbol: 'ADANIGREEN',  name: 'Adani Green Energy Ltd' },
  { symbol: 'ADANITRANS',  name: 'Adani Transmission Ltd' },
  { symbol: 'ADANIPOWER',  name: 'Adani Power Ltd' },
  { symbol: 'AMBUJACEM',   name: 'Ambuja Cements Ltd' },
  { symbol: 'AUROPHARMA',  name: 'Aurobindo Pharma Ltd' },
  { symbol: 'BANKBARODA',  name: 'Bank of Baroda' },
  { symbol: 'BERGEPAINT',  name: 'Berger Paints India Ltd' },
  { symbol: 'BOSCHLTD',    name: 'Bosch Ltd' },
  { symbol: 'CANBK',       name: 'Canara Bank' },
  { symbol: 'CHOLAFIN',    name: 'Cholamandalam Investment and Finance Company Ltd' },
  { symbol: 'COLPAL',      name: 'Colgate-Palmolive (India) Ltd' },
  { symbol: 'CONCOR',      name: 'Container Corporation of India Ltd' },
  { symbol: 'DABUR',       name: 'Dabur India Ltd' },
  { symbol: 'DEEPAKNTR',   name: 'Deepak Nitrite Ltd' },
  { symbol: 'DLF',         name: 'DLF Ltd' },
  { symbol: 'GAIL',        name: 'GAIL (India) Ltd' },
  { symbol: 'GODREJCP',    name: 'Godrej Consumer Products Ltd' },
  { symbol: 'GODREJPROP',  name: 'Godrej Properties Ltd' },
  { symbol: 'HAVELLS',     name: 'Havells India Ltd' },
  { symbol: 'HDFCAMC',     name: 'HDFC Asset Management Company Ltd' },
  { symbol: 'ICICIPRULI',  name: 'ICICI Prudential Life Insurance Company Ltd' },
  { symbol: 'INDUSTOWER',  name: 'Indus Towers Ltd' },
  { symbol: 'IRCTC',       name: 'Indian Railway Catering and Tourism Corporation Ltd' },
  { symbol: 'JINDALSTEL',  name: 'Jindal Steel & Power Ltd' },
  { symbol: 'JUBLFOOD',    name: 'Jubilant FoodWorks Ltd' },
  { symbol: 'LUPIN',       name: 'Lupin Ltd' },
  { symbol: 'MARICO',      name: 'Marico Ltd' },
  { symbol: 'MUTHOOTFIN',  name: 'Muthoot Finance Ltd' },
  { symbol: 'NAUKRI',      name: 'Info Edge (India) Ltd' },
  { symbol: 'OBEROIRLTY',  name: 'Oberoi Realty Ltd' },
  { symbol: 'OFSS',        name: 'Oracle Financial Services Software Ltd' },
  { symbol: 'PAGEIND',     name: 'Page Industries Ltd' },
  { symbol: 'PERSISTENT',  name: 'Persistent Systems Ltd' },
  { symbol: 'PETRONET',    name: 'Petronet LNG Ltd' },
  { symbol: 'PIDILITIND',  name: 'Pidilite Industries Ltd' },
  { symbol: 'PNB',         name: 'Punjab National Bank' },
  { symbol: 'POLYCAB',     name: 'Polycab India Ltd' },
  { symbol: 'RECLTD',      name: 'REC Ltd' },
  { symbol: 'SAIL',        name: 'Steel Authority of India Ltd' },
  { symbol: 'SBICARD',     name: 'SBI Cards and Payment Services Ltd' },
  { symbol: 'SIEMENS',     name: 'Siemens Ltd' },
  { symbol: 'TATACONSUM',  name: 'Tata Consumer Products Ltd' },
  { symbol: 'TORNTPHARM',  name: 'Torrent Pharmaceuticals Ltd' },
  { symbol: 'TRENT',       name: 'Trent Ltd' },
  { symbol: 'UBL',         name: 'United Breweries Ltd' },
  { symbol: 'VEDL',        name: 'Vedanta Ltd' },
  { symbol: 'VOLTAS',      name: 'Voltas Ltd' },
  { symbol: 'ZOMATO',      name: 'Zomato Ltd' },
  { symbol: 'ZYDUSLIFE',   name: 'Zydus Lifesciences Ltd' },

  // ── POPULAR MID & SMALL CAP ───────────────────────────────────
  { symbol: 'ABB',         name: 'ABB India Ltd' },
  { symbol: 'ABCAPITAL',   name: 'Aditya Birla Capital Ltd' },
  { symbol: 'ABFRL',       name: 'Aditya Birla Fashion and Retail Ltd' },
  { symbol: 'ALKEM',       name: 'Alkem Laboratories Ltd' },
  { symbol: 'ALOKINDS',    name: 'Alok Industries Ltd' },
  { symbol: 'APLLTD',      name: 'Alembic Pharmaceuticals Ltd' },
  { symbol: 'ASTRAL',      name: 'Astral Ltd' },
  { symbol: 'ATGL',        name: 'Adani Total Gas Ltd' },
  { symbol: 'ATUL',        name: 'Atul Ltd' },
  { symbol: 'AWHCL',       name: 'Amrit Wilson Hotels & Clubs Ltd' },
  { symbol: 'BALKRISIND',  name: 'Balkrishna Industries Ltd' },
  { symbol: 'BANDHANBNK',  name: 'Bandhan Bank Ltd' },
  { symbol: 'BEL',         name: 'Bharat Electronics Ltd' },
  { symbol: 'BHEL',        name: 'Bharat Heavy Electricals Ltd' },
  { symbol: 'BIOCON',      name: 'Biocon Ltd' },
  { symbol: 'CANFINHOME',  name: 'Can Fin Homes Ltd' },
  { symbol: 'CASTROLIND',  name: 'Castrol India Ltd' },
  { symbol: 'CEATLTD',     name: 'CEAT Ltd' },
  { symbol: 'CENTURYTEX',  name: 'Century Textiles & Industries Ltd' },
  { symbol: 'CESC',        name: 'CESC Ltd' },
  { symbol: 'CHAMBLFERT',  name: 'Chambal Fertilizers & Chemicals Ltd' },
  { symbol: 'COFORGE',     name: 'Coforge Ltd' },
  { symbol: 'CROMPTON',    name: 'Crompton Greaves Consumer Electricals Ltd' },
  { symbol: 'CUMMINSIND',  name: 'Cummins India Ltd' },
  { symbol: 'DALBHARAT',   name: 'Dalmia Bharat Ltd' },
  { symbol: 'DELHIVERY',   name: 'Delhivery Ltd' },
  { symbol: 'DIXON',       name: 'Dixon Technologies (India) Ltd' },
  { symbol: 'EMAMILTD',    name: 'Emami Ltd' },
  { symbol: 'ENDURANCE',   name: 'Endurance Technologies Ltd' },
  { symbol: 'ESCORTS',     name: 'Escorts Kubota Ltd' },
  { symbol: 'EXIDEIND',    name: 'Exide Industries Ltd' },
  { symbol: 'FACT',        name: 'Fertilizers and Chemicals Travancore Ltd' },
  { symbol: 'FEDERALBNK',  name: 'Federal Bank Ltd' },
  { symbol: 'FORTIS',      name: 'Fortis Healthcare Ltd' },
  { symbol: 'FSL',         name: 'Firstsource Solutions Ltd' },
  { symbol: 'GLAXO',       name: 'GlaxoSmithKline Pharmaceuticals Ltd' },
  { symbol: 'GMRINFRA',    name: 'GMR Airports Infrastructure Ltd' },
  { symbol: 'GNFC',        name: 'Gujarat Narmada Valley Fertilizers & Chemicals Ltd' },
  { symbol: 'GPIL',        name: 'Godawari Power & Ispat Ltd' },
  { symbol: 'GRANULES',    name: 'Granules India Ltd' },
  { symbol: 'GSPL',        name: 'Gujarat State Petronet Ltd' },
  { symbol: 'HAPPSTMNDS',  name: 'Happiest Minds Technologies Ltd' },
  { symbol: 'HDFCBANK',    name: 'HDFC Bank Ltd' },
  { symbol: 'HINDPETRO',   name: 'Hindustan Petroleum Corporation Ltd' },
  { symbol: 'HONAUT',      name: 'Honeywell Automation India Ltd' },
  { symbol: 'IDBI',        name: 'IDBI Bank Ltd' },
  { symbol: 'IDFCFIRSTB',  name: 'IDFC First Bank Ltd' },
  { symbol: 'IEX',         name: 'Indian Energy Exchange Ltd' },
  { symbol: 'IPCALAB',     name: 'IPCA Laboratories Ltd' },
  { symbol: 'IRB',         name: 'IRB Infrastructure Developers Ltd' },
  { symbol: 'IRFC',        name: 'Indian Railway Finance Corporation Ltd' },
  { symbol: 'ISEC',        name: 'ICICI Securities Ltd' },
  { symbol: 'IGL',         name: 'Indraprastha Gas Ltd' },
  { symbol: 'JKCEMENT',    name: 'JK Cement Ltd' },
  { symbol: 'JSWENERGY',   name: 'JSW Energy Ltd' },
  { symbol: 'KAJARIACER',  name: 'Kajaria Ceramics Ltd' },
  { symbol: 'KANSAINER',   name: 'Kansai Nerolac Paints Ltd' },
  { symbol: 'KEC',         name: 'KEC International Ltd' },
  { symbol: 'KPITTECH',    name: 'KPIT Technologies Ltd' },
  { symbol: 'LALPATHLAB',  name: 'Dr Lal PathLabs Ltd' },
  { symbol: 'LAURUSLABS',  name: 'Laurus Labs Ltd' },
  { symbol: 'LICHSGFIN',   name: 'LIC Housing Finance Ltd' },
  { symbol: 'LINDEINDIA',  name: 'Linde India Ltd' },
  { symbol: 'LTTS',        name: 'L&T Technology Services Ltd' },
  { symbol: 'LUXIND',      name: 'Lux Industries Ltd' },
  { symbol: 'MANAPPURAM',  name: 'Manappuram Finance Ltd' },
  { symbol: 'MAZDOCK',     name: 'Mazagon Dock Shipbuilders Ltd' },
  { symbol: 'MCX',         name: 'Multi Commodity Exchange of India Ltd' },
  { symbol: 'METROPOLIS',  name: 'Metropolis Healthcare Ltd' },
  { symbol: 'MFSL',        name: 'Max Financial Services Ltd' },
  { symbol: 'MINDTREE',    name: 'Mindtree Ltd' },
  { symbol: 'MGL',         name: 'Mahanagar Gas Ltd' },
  { symbol: 'MOTHERSON',   name: 'Samvardhana Motherson International Ltd' },
  { symbol: 'MPHASIS',     name: 'Mphasis Ltd' },
  { symbol: 'MRF',         name: 'MRF Ltd' },
  { symbol: 'NAVINFLUOR',  name: 'Navin Fluorine International Ltd' },
  { symbol: 'NHPC',        name: 'NHPC Ltd' },
  { symbol: 'NMDC',        name: 'NMDC Ltd' },
  { symbol: 'NLCINDIA',    name: 'NLC India Ltd' },
  { symbol: 'NYKAA',       name: 'FSN E-Commerce Ventures Ltd (Nykaa)' },
  { symbol: 'ICICIGI',     name: 'ICICI Lombard General Insurance Company Ltd' },
  { symbol: 'PAYTM',       name: 'One97 Communications Ltd (Paytm)' },
  { symbol: 'PCBL',        name: 'PCBL Ltd' },
  { symbol: 'PFIZER',      name: 'Pfizer Ltd' },
  { symbol: 'PGHH',        name: 'Procter & Gamble Hygiene and Health Care Ltd' },
  { symbol: 'PHOENIXLTD',  name: 'Phoenix Mills Ltd' },
  { symbol: 'PIIND',       name: 'PI Industries Ltd' },
  { symbol: 'POLICYBZR',   name: 'PB Fintech Ltd (Policybazaar)' },
  { symbol: 'PRAJIND',     name: 'Praj Industries Ltd' },
  { symbol: 'PRESTIGE',    name: 'Prestige Estates Projects Ltd' },
  { symbol: 'PVRINOX',     name: 'PVR INOX Ltd' },
  { symbol: 'RAMCOCEM',    name: 'The Ramco Cements Ltd' },
  { symbol: 'RBLBANK',     name: 'RBL Bank Ltd' },
  { symbol: 'RITES',       name: 'RITES Ltd' },
  { symbol: 'ROUTE',       name: 'Route Mobile Ltd' },
  { symbol: 'SJVN',        name: 'SJVN Ltd' },
  { symbol: 'SONACOMS',    name: 'Sona BLW Precision Forgings Ltd' },
  { symbol: 'SOLARINDS',   name: 'Solar Industries India Ltd' },
  { symbol: 'STAR',        name: 'Star Health and Allied Insurance Company Ltd' },
  { symbol: 'SUMICHEM',    name: 'Sumitomo Chemical India Ltd' },
  { symbol: 'SUPREMEIND',  name: 'Supreme Industries Ltd' },
  { symbol: 'SUZLON',      name: 'Suzlon Energy Ltd' },
  { symbol: 'TANLA',       name: 'Tanla Platforms Ltd' },
  { symbol: 'TATACOMM',    name: 'Tata Communications Ltd' },
  { symbol: 'TATAELXSI',   name: 'Tata Elxsi Ltd' },
  { symbol: 'TATAMTRDVR',  name: 'Tata Motors DVR' },
  { symbol: 'TATAPOWER',   name: 'Tata Power Company Ltd' },
  { symbol: 'TCNSBRANDS',  name: 'TCNS Clothing Company Ltd' },
  { symbol: 'THERMAX',     name: 'Thermax Ltd' },
  { symbol: 'TIMKEN',      name: 'Timken India Ltd' },
  { symbol: 'TIINDIA',     name: 'Tube Investments of India Ltd' },
  { symbol: 'TORNTPOWER',  name: 'Torrent Power Ltd' },
  { symbol: 'TTKPRESTIG',  name: 'TTK Prestige Ltd' },
  { symbol: 'TV18BRDCST',  name: 'TV18 Broadcast Ltd' },
  { symbol: 'TVSMOTOR',    name: 'TVS Motor Company Ltd' },
  { symbol: 'UPL',         name: 'UPL Ltd' },
  { symbol: 'UTIAMC',      name: 'UTI Asset Management Company Ltd' },
  { symbol: 'VGUARD',      name: 'V-Guard Industries Ltd' },
  { symbol: 'VINDHYATEL',  name: 'Vindhya Telelinks Ltd' },
  { symbol: 'VMART',       name: 'V-Mart Retail Ltd' },
  { symbol: 'WHIRLPOOL',   name: 'Whirlpool of India Ltd' },
  { symbol: 'WOCKPHARMA',  name: 'Wockhardt Ltd' },
  { symbol: 'YESBANK',     name: 'Yes Bank Ltd' },
  { symbol: 'ZEEL',        name: 'Zee Entertainment Enterprises Ltd' },
  { symbol: 'ZENTEC',      name: 'Zensar Technologies Ltd' },
];
